url: https://a5053c.github.io
baseurl: /a5053c-2/

# Site settings
title: IT Security Consulting
email: andro.schulz@gmail.com
description: "SIEM Consulting, CDC / SOC setup, SOAR service, Security Incident Response"


# Team names, titles and social links
people:
- name: Andro Schulz
  pic: 1
  position: Lead Consultant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Berlin DownTown
  - line: Berlin 10005

# Build settings
markdown: kramdown
permalink: pretty
